#+TITLE: Anomaly Explain
#+AUTHOR: Leilani H. Gilpin
#+EMAIL: lgilpin@ucsc.edu
#+STARTUP: hidestars indent

This is the anomaly detection through explanations (ADE)
architecture.  It compromises of two systems:
1. A system level architecture (ADE) which uses a synthesizer to
  reconcile failures amongst a set of reasonableness monitors.
2. Reasonableness monitors for each subsystem.
   
* Commonsense
The monitor supports commonsense from NextKB (companion_kb.py) and
ConceptNet (conceptnet.py).  

The commonsense data is stored as a list of facts (see Fact in
logical_classes.py) for a particular query or queries.  The list of
facts can be operated on as a list or as a dataframe.  

Run conceptNet tests with:
#+BEGIN_SRC
python3 system_tests/test_conceptnet.py -m unittest
#+END_SRC

** Reasonableness monitor
Reasonableness monitors are able to explain why a fact or list of
facts are reasonable.  They build up [[Commonsense]] knowledge, and
develop an explanation why a fact is reasonable or not.  These
monitors can be catered to a particular set of relations or not. 
** Synthesizer
* Tasks
** TODO Common representation for using facts
** TODO Chain together explanations
** TODO Test suite
- Tests are scattered throughout the repo.  The most recent tests are
  in commonsense/tests and should probably be put somewhere else in
  the repo. 
